default:
  image: ubuntu:23.10
check_code:
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get upgrade -y && xargs apt-get install -y < apt-packages.txt
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    - brew bundle install --file=ubuntu.Brewfile
    - npm install --global yarn && yarn install
  script:
    - tools/composer run parallel-lint
    - yarn check:size
    - yarn lint
    - yarn analysis
    - npx editorconfig-checker
  when: manual
