
# Homebrew dev packages (tested on macOS, but may work on Linux distros too)

brew "bash"
brew "coreutils"
brew "file"
brew "gifsicle"
brew "gpg"
brew "hadolint"
brew "icu4c", link: true
brew "imagemagick"
brew "jpeginfo"
brew "jpegoptim"
brew "jq"
brew "maven"
brew "mdbtools"
brew "nodejs"
brew "npm"
brew "optipng"
brew "oxipng"
brew "php"
brew "pngcheck"
brew "pngquant"
brew "shellcheck"
brew "shfmt"
brew "tidy-html5"
brew "unar"
brew "webp"
brew "yamllint"
