version: "3"
services:
  webserver-alpine:
    build:
      context: .
      dockerfile: .docker/alpine.Dockerfile
    image: alpine-apache2-php8
    container_name: pccd-web-alpine
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pccd}
      MYSQL_USER: ${MYSQL_USER:-pccd}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: mysql
      WEB_ADMIN_PASSWORD: ${WEB_ADMIN_PASSWORD}
      OPENAI_KEY: ${OPENAI_KEY}
    ports:
      - ${APACHE_HTTP_PORT:-8080}:80
    restart: unless-stopped
  mysql:
    image: mariadb:10.5.23-focal
    container_name: pccd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pccd}
      MYSQL_USER: ${MYSQL_USER:-pccd}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./.docker/mysql:/etc/mysql/conf.d"
      - "./install/db:/docker-entrypoint-initdb.d"
