version: "3"
services:
  build:
    build:
      context: .
      dockerfile: .docker/ubuntu.build.Dockerfile
    image: ubuntu-build
    container_name: pccd-build
    volumes:
      - "./:/srv/app"
