<?php

/**
 * This file is part of PCCD.
 *
 * (c) Pere Orga Esteve <pere@orga.cat>
 * (c) Víctor Pàmies i Riudor <vpamies@gmail.com>
 *
 * This source file is subject to the AGPL license that is bundled with this
 * source code in the file LICENSE.
 */

declare(strict_types=1);

// Manual redirects mapping.

// These redirects are mapped manually based on a Google Search console report.
$redirects = [
    "/obra/Marrugat_Cuy%C3%A0s%2C_Ramon_(2018)%3A_Alguna_cosa_m%C3%A9s_que_l'anar_a_tocar_ferro" => '/obra/Marrugat_Cuyàs%2C_Ramon_%282018%29%3A_«Alguna_cosa_més_que_l%27anar_a_tocar_ferro»._La_fraseologia_tarragonina',
    "/p/Ni_fe_d'enc%C3%A0rrec" => '/p/Ni_fet_d%27enc%C3%A0rrec',
    '/?obra=Badia+i+Pujol%2C+Jordi+%282021%29%3A+Ras+i+curt+-+Fer+un+%E2%80%98polvo%E2%80%99+o+fotre+un+clau%3F%3A+aquesta+%C3%A9s+la+q%C3%BCesti%C3%B3' => '/obra/Badia_i_Pujol%2C_Jordi_%282022%29%3A_Ras_i_curt_-_Deu_refranys_catalans_intradu%C3%AFbles',
    '/?obra=Badia+i+Pujol%2C+Jordi+(2021):+Ras+i+curt+-+Fer+un+%E2%80%98polvo%E2%80%99+o+fotre+un+clau?:+aquesta+%C3%A9s+la+q%C3%BCesti%C3%B3' => '/obra/Badia_i_Pujol%2C_Jordi_%282022%29%3A_Ras_i_curt_-_Deu_refranys_catalans_intradu%C3%AFbles',
    '/?obra=Badia+i+Pujol,+Jordi+(2021):+Ras+i+curt+-+Fer+un+%E2%80%98polvo%E2%80%99+o+fotre+un+clau?:+aquesta+%C3%A9s+la+q%C3%BCesti%C3%B3' => '/obra/Badia_i_Pujol%2C_Jordi_%282022%29%3A_Ras_i_curt_-_Deu_refranys_catalans_intradu%C3%AFbles',
    '/?obra=Marrugat+Cuy%C3%A0s%2C+Ramon+%282018%29%3A+Alguna+cosa+m%C3%A9s+que+l%27anar+a+tocar+ferro' => '/obra/Marrugat_Cuyàs%2C_Ramon_%282018%29%3A_«Alguna_cosa_més_que_l%27anar_a_tocar_ferro»._La_fraseologia_tarragonina',
    '/?obra=Marrugat+Cuy%C3%A0s%2C+Ramon+(2018):+Alguna+cosa+m%C3%A9s+que+l%27anar+a+tocar+ferro' => '/obra/Marrugat_Cuyàs%2C_Ramon_%282018%29%3A_«Alguna_cosa_més_que_l%27anar_a_tocar_ferro»._La_fraseologia_tarragonina',
    '/?obra=Marrugat+Cuy%C3%A0s,+Ramon+(2018):+Alguna+cosa+m%C3%A9s+que+l%27anar+a+tocar+ferro' => '/obra/Marrugat_Cuyàs%2C_Ramon_%282018%29%3A_«Alguna_cosa_més_que_l%27anar_a_tocar_ferro»._La_fraseologia_tarragonina',
    '/?obra=Mettmann%2C+Walter+%281989%29%3A+%C2%ABProverbia+arabum%C2%BB+eine+altkatalanische+sprichw%C3%B6rter-Uns+sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/?obra=Mettmann%2C+Walter+(1989):+%C2%ABProverbia+arabum%C2%BB+eine+altkatalanische+sprichw%C3%B6rter-Uns+sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/?obra=Mettmann,+Walter+(1989):+%C2%ABProverbia+arabum%C2%BB+eine+altkatalanische+sprichw%C3%B6rter-Uns+sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/?obra=Mettmann.%2C+Walter+%281989%29%3A+%C2%ABProverbia+arabum%C2%BB+eine+altkatalanische+sprichw%C3%B6rter-Uns+sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/?obra=Mettmann.%2C+Walter+(1989):+%C2%ABProverbia+arabum%C2%BB+eine+altkatalanische+sprichw%C3%B6rter-Uns+sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/?obra=Mettmann.,+Walter+(1989):+%C2%ABProverbia+arabum%C2%BB+eine+altkatalanische+sprichw%C3%B6rter-Uns+sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/?obra=Revista+S%27Uni%C3%B3+de+S%27Arenal+%281988-1996%29' => '/obra/S%27Unió_de_S%27Arenal_%281988-1996%29',
    '/?obra=Revista+S%27Uni%C3%B3+de+S%27Arenal+(1988-1996)' => '/obra/S%27Unió_de_S%27Arenal_%281988-1996%29',
    '/?paremiotipus=%C3%A9s+dolent+que+la+carn+de+gos' => '/p/Dolent_com_la_carn_de_gos',
    '/?paremiotipus=A+judici+i+pagar%C2%ABlo%C2%BB+judicat' => '/p/A_judici_i_pagar_«lo»_judicat',
    '/?paremiotipus=A+l%27Ascensi%C3%B3+cireretes+abundo+A+Val%C3%A8ncia%E2%80%A6+que+aqu%C3%AD+no' => '/p/Per_l%27Ascensió%2C_cireretes_en_abundor',
    '/?paremiotipus=A+l%27Ascensió+cireretes+abundo+A+València…+que+aquí+no' => '/p/Per_l%27Ascensió%2C_cireretes_en_abundor',
    '/?paremiotipus=A+l%27aire+llure' => '/p/A_l%27aire_lliure',
    '/?paremiotipus=C%C3%A0cilment' => '/p/D%C3%B2cilment',
    '/?paremiotipus=Camina+que+caminara%CC%80s' => '/p/Camina_que_caminar%C3%A0s',
    '/?paremiotipus=Coll+avalll' => '/p/Coll_avall',
    '/?paremiotipus=Com+e+p%C3%A8l+de+la+pasta' => '/p/Com_el_p%C3%A8l_de_la_pasta',
    '/?paremiotipus=Com+un+eix+a+l%27aigua' => '/p/Com_un_peix_a_l%27aigua',
    '/?paremiotipus=Cre%CC%81ixer+com+una+mala+herba' => '/p/Créixer_com_una_mala_herba',
    '/?paremiotipus=Decloure+les+mans' => '/p/Descloure_les_mans',
    '/?paremiotipus=Deixar+a+manlleu' => '/p/Anar_a_manlleu',
    '/?paremiotipus=Diu+el+bou+pel+febrer:+-Prou+aigua%2C+que+se%27m+podreix+la+banya' => '/p/Diu_el_bou_pel_febrer%3A_-_Pluja%2C_pluja%2C_fins_que_se%27m_podreixi_la_cua',
    '/?paremiotipus=Dona+d%27altre+marit%2C+olla+de+caldo+afegitDona+d%27altre+marit%2C+olla+de+caldo+afegit' => '/p/Dona_d%27altre_marit%2C_olla_de_caldo_afegit',
    '/?paremiotipus=El+perol+diu+a+la+paella%3A+si+m%27embrutes%2C+t%27emmascaroSer+el+rei+del+mambo' => '/p/El_perol_diu_a_la_paella%3A_si_m%27embrutes%2C_t%27emmascaro',
    '/?paremiotipus=El+perol+diu+a+la+paella:+si+m%27embrutes%2C+t%27emmascaroSer+el+rei+del+mambo' => '/p/El_perol_diu_a_la_paella%3A_si_m%27embrutes%2C_t%27emmascaro',
    '/?paremiotipus=El+perol+diu+a+la+paella:+si+m%27embrutes,+t%27emmascaroSer+el+rei+del+mambo' => '/p/El_perol_diu_a_la_paella%3A_si_m%27embrutes%2C_t%27emmascaro',
    '/?paremiotipus=En+X%C3%A0bia%2C+desculats%3B+en+Ondara%2C+fanfarrons%3B+en+Benissa%2C+senyorets%2C+i+en+Teulada%2C+boquimollls' => '/p/En_X%C3%A0bia%2C_desculats%3B_en_Ondara%2C_fanfarrons%3B_en_Benissa%2C_senyorets%2C_i_en_Teulada%2C_boquimolls',
    '/?paremiotipus=En+Xàbia,+desculats;+en+Ondara,+fanfarrons;+en+Benissa,+senyorets,+i+en+Teulada,+boquimollls' => '/p/En_X%C3%A0bia%2C_desculats%3B_en_Ondara%2C_fanfarrons%3B_en_Benissa%2C_senyorets%2C_i_en_Teulada%2C_boquimolls',
    '/?paremiotipus=Fer+me%CC%81s+badalls+que+rots' => '/p/Fer_m%C3%A9s_badalls_que_rots',
    '/?paremiotipus=Fer+uin+merder' => '/p/Fer_merder',
    '/?paremiotipus=Fer-li+una+mala+jugada' => '/p/Mala_jugada',
    '/?paremiotipus=Ja+ports+xiular+si+l%27ase+no+vol+beure' => '/p/Ja_pots_xiular_si_l%27ase_no_vol_beure',
    '/?paremiotipus=Jugar-li+una+mala+passada' => '/p/Fer-li_una_mala_passada',
    '/?paremiotipus=Les+xiques+de+Vilella+(o+del+Poretal+d%27Horta%2C+o+de+Guardamar%2C+o+de+Torrevella+o+del+Vilar)%2C+a+la+llum+diuen+%C2%ABcandil%C2%BB%2C+a+la+finestra%2C+%C2%ABventana%C2%BB+i+al+julivert%2C+%C2%ABperegil%C2%BB' => '/p/Sas%2C_Malp%C3%A0s%2C_Peranera_i_Castell%C3%A0s%2C_Sent%C3%ADs%2C_C%C3%A9rvoles_i_Naens%3A_els_set_pobles_m%C3%A9s_dolents._Si_n%27hi_voleu_m%C3%A9s%2C_poseu-hi_Ben%C3%A9s%2C_si_no_n%27hi_ha_prou%2C_poseu-hi_Castellnou._Si_n%27hi_voleu_una_bona_renglera%2C_poseu-hi_tota_la_vall_de_Cabdella',
    '/?paremiotipus=Les+xiques+de+Vilella+o+del+Poretal+d%27Horta%2C+o+de+Guardamar%2C+o+de+Torrevella+o+del+Vilar%2C+a+la+llum+diuen+%C2%ABcandil%C2%BB%2C+a+la+finestra%2C+%C2%ABventana%C2%BB+i+al+julivert%2C+%C2%ABperegil%C2%BB' => '/p/Sas%2C_Malp%C3%A0s%2C_Peranera_i_Castell%C3%A0s%2C_Sent%C3%ADs%2C_C%C3%A9rvoles_i_Naens%3A_els_set_pobles_m%C3%A9s_dolents._Si_n%27hi_voleu_m%C3%A9s%2C_poseu-hi_Ben%C3%A9s%2C_si_no_n%27hi_ha_prou%2C_poseu-hi_Castellnou._Si_n%27hi_voleu_una_bona_renglera%2C_poseu-hi_tota_la_vall_de_Cabdella',
    '/?paremiotipus=Ni+fe+d%27enc%C3%A0rrec' => '/p/Ni_fet_d%27enc%C3%A0rrec',
    '/?paremiotipus=Ofegar-se+en+nu+got+d%27aigua' => '/p/Ofegar-se_en_un_got_d%27aigua',
    '/?paremiotipus=Ognominiosament' => '/p/Ignominiosament',
    '/?paremiotipus=Parar+taula' => '/p/Parar_taula',
    '/?paremiotipus=Passarse-li+l%27arr%C3%B2s' => '/p/Passar-se-li_l%27arr%C3%B2s',
    '/?paremiotipus=Passr+el+rosari' => '/p/Passar_el_rosari',
    '/?paremiotipus=Pel+setembre+o+desembre%2C+qui+tingui+blat%2C+que+en+sembri' => '/p/Pel_setembre%2C_qui_tingui_blat%2C_que_en_sembri',
    '/?paremiotipus=Posr+en+gu%C3%A0rdia' => '/p/Posar_en_guàrdia',
    '/?paremiotipus=Posra+barba' => '/p/Posar_barba',
    '/?paremiotipus=Prendre+a+manlleu' => '/p/Anar_a_manlleu',
    '/?paremiotipus=Quan+la+Murta+s%27emborrasca+i+la+Casella+o+Matamon+fa+capell%2C+llaurador%2C+ves-te%27n+a+casa%2C+pica+espart+i+fes+cordell' => '/p/Pica_espart_i_fes_cordell',
    '/?paremiotipus=Rompre-li+la+crisma' => '/p/Trencar_o_rompre_la_crisma',
    '/?paremiotipus=Romprer-li+el+cap' => '/p/Trencar-li_el_cap',
    '/?paremiotipus=Ser+un+figa+blana' => '/p/Figa_blana',
    '/?paremiotipus=Ser+un+figa+tova' => '/p/Figa_tova',
    '/?paremiotipus=Si+tens+una+filla+que+no+l%27estimis+gaire%2C+casa-la+a+Albons%2C+o+a+Bellcaire%2C+o+sin%C3%83%C2%B3+a+Vilademat%2C+que+ser%C3%83%C2%A0+morta+m%C3%83%C2%A9s+aviat' => '/p/Si_tens_una_filla_que_no_l%27estimis_gaire%2C_casa-la_a_Albons%2C_o_a_Bellcaire%2C_o_sin%C3%B3_a_Vilademat%2C_que_ser%C3%A0_morta_m%C3%A9s_aviat',
    '/?paremiotipus=Terra+on+vas%2C+costum+hi+trobes' => '/p/A_terra_que_vas%2C_usan%C3%A7a_o_costums_que_trobes',
    '/?paremiotipus=Tots+els+mosquits+volen+prendre+tabaco' => '/p/Totes_les_mosques_tenen_tos_i_els_mosquits_prenen_tabac',
    '/?paremiotipus=Treure-hi+la+pols' => '/p/Treure_la_pols',
    '/?paremiotipus=Treureli+la+son' => '/p/Treure-li_la_son',
    '/?paremiotipus=Vaig+anar+a+Constantinoble+i+al+punt+em+varen+constantinoblitzar+tan+b%C3%A9%2C+que+ara+cap+desconstantinoblitzador+no+f%C3%B3ra+poru+per+desconstantinoblitzar-me%2C+encara+que+fos+el+primer+desconstantinoblitzador+de+tots+els+desconstantinoblitzadors+de+Constantinoble' => '/p/Vaig_anar_a_Constantinoble_i_al_punt_em_varen_constantinoblitzar_tan_b%C3%A9%2C_que_ara_cap_desconstantinoblitzador_no_f%C3%B3ra_prou_per_desconstantinoblitzar-me%2C_encara_que_fos_el_primer_desconstantinoblitzador_de_tots_els_desconstantinoblitzadors_de_Constantinoble',
    '/?paremiotipus=anera+i+Castell%C3%A0s%2C+Sent%C3%ADs%2C+C%C3%A9rvoles+i+Naens:+els+set+pobles+m%C3%A9s+dolents.+Si+n%27hi+voleu+m%C3%A9s%2C+poseu-hi+Ben%C3%A9s%2C+si+no+n%27hi+ha+prou%2C+poseu-hi+Castellnou.+Si+n%27hi+voleu+una+bona+renglera%2C+poseu-hi+tota+la+vall+de+Cabdella' => '/p/Sas%2C_Malp%C3%A0s%2C_Peranera_i_Castell%C3%A0s%2C_Sent%C3%ADs%2C_C%C3%A9rvoles_i_Naens%3A_els_set_pobles_m%C3%A9s_dolents._Si_n%27hi_voleu_m%C3%A9s%2C_poseu-hi_Ben%C3%A9s%2C_si_no_n%27hi_ha_prou%2C_poseu-hi_Castellnou._Si_n%27hi_voleu_una_bona_renglera%2C_poseu-hi_tota_la_vall_de_Cabdella',
    '/?paremiotipus=ap+pelat%2C+de+Viladamat' => '/p/Cap_pelat%2C_de_Viladamat',
    '/?paremiotipus=ap+pelat,+de+Viladamat' => '/p/Cap_pelat%2C_de_Viladamat',
    '/?paremiotipus=ell%C3%B3%2C+venen+oli%3B+a+Alpicat%2C+venen+els+alls%2C+i+a+Almenar%2C+fan+l%27allioli' => '/p/A_Peralta%2C_venen_sal%3B_a_Rosselló%2C_venen_oli%3B_a_Alpicat%2C_venen_els_alls%2C_i_a_Almenar%2C_fan_l%27allioli',
    '/?paremiotipus=ell%C3%B3,%20venen%20oli;%20a%20Alpicat,%20venen%20els%20alls,%20i%20a%20Almenar,%20fan%20l%27allioli' => '/p/A_Peralta%2C_venen_sal%3B_a_Rosselló%2C_venen_oli%3B_a_Alpicat%2C_venen_els_alls%2C_i_a_Almenar%2C_fan_l%27allioli',
    '/?paremiotipus=ell%C3%B3,+venen+oli;+a+Alpicat,+venen+els+alls,+i+a+Almenar,+fan+l%27allioli' => '/p/A_Peralta%2C_venen_sal%3B_a_Rosselló%2C_venen_oli%3B_a_Alpicat%2C_venen_els_alls%2C_i_a_Almenar%2C_fan_l%27allioli',
    '/?paremiotipus=elló,+venen+oli;+a+Alpicat,+venen+els+alls,+i+a+Almenar,+fan+l%27allioli' => '/p/A_Peralta%2C_venen_sal%3B_a_Rosselló%2C_venen_oli%3B_a_Alpicat%2C_venen_els_alls%2C_i_a_Almenar%2C_fan_l%27allioli',
    '/?paremiotipus=escansar+despr%C3%A9s+de+dinar+%C3%A9s+salut+que+es+pot+donar' => '/p/Descansar_despr%C3%A9s_de_dinar_%C3%A9s_salut_que_es_pot_donar',
    '/?paremiotipus=n+canyissos%2C+a+la+Torre+fan+sab%C3%B3+i+a+Garcia+fan+cabestres+per+a+tots+els+rucots+d%27Asc%C3%B3' => '/p/A_Vinebre_fan_canyissos%2C_a_la_Torre_fan_sab%C3%B3_i_a_Garcia_fan_cabestres_per_tots_els_rucots_d%27Asc%C3%B3',
    '/?paremiotipus=oA+pas+de+bou' => '/p/A_pas_de_bou',
    '/?paremiotipus=ure-se-li+el+llaut%C3%B3' => '/p/Veure-se-li_el_llautó',
    '/obra/Casta%C3%B1eda%2C_Vicente_%281919-20%29%3A_Refranes_valencianos_recopilados_por_el_P._Luis_Galiana%2C_Dominico' => '/obra/Castañeda%2C_Vicente_%281770%29%3A_Refranes_valencianos_recopilados_por_el_P._Luis_Galiana%2C_Dominico%2C_ed._1919-20',
    '/obra/Casta%C3%B1eda%2C_Vicente_(1919-20)%3A_Refranes_valencianos_recopilados_por_el_P._Luis_Galiana%2C_Dominico' => '/obra/Castañeda%2C_Vicente_%281770%29%3A_Refranes_valencianos_recopilados_por_el_P._Luis_Galiana%2C_Dominico%2C_ed._1919-20',
    '/obra/Casta%c3%b1eda%2C_Vicente_(1919-20):_Refranes_valencianos_recopilados_por_el_P._Luis_Galiana%2C_Dominico' => '/obra/Castañeda%2C_Vicente_%281770%29%3A_Refranes_valencianos_recopilados_por_el_P._Luis_Galiana%2C_Dominico%2C_ed._1919-20',
    '/obra/Marrugat_Cuy%C3%A0s%2C_Ramon_%282018%29%3A_Alguna_cosa_m%C3%A9s_que_l%27anar_a_tocar_ferro' => '/obra/Marrugat_Cuyàs%2C_Ramon_%282018%29%3A_«Alguna_cosa_més_que_l%27anar_a_tocar_ferro»._La_fraseologia_tarragonina',
    '/obra/Marrugat_Cuy%c3%a0s%2C_Ramon_(2018):_Alguna_cosa_m%c3%a9s_que_l%27anar_a_tocar_ferro' => '/obra/Marrugat_Cuyàs%2C_Ramon_%282018%29%3A_«Alguna_cosa_més_que_l%27anar_a_tocar_ferro»._La_fraseologia_tarragonina',
    '/obra/Mettmann%2C_Walter_%281989%29%3A_%C2%ABProverbia_arabum%C2%BB_eine_altkatalanische_sprichw%C3%B6rter-Uns_sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/obra/Mettmann%2C_Walter_(1989)%3A_%C2%ABProverbia_arabum%C2%BB_eine_altkatalanische_sprichw%C3%B6rter-Uns_sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/obra/Mettmann%2C_Walter_(1989):_%c2%abProverbia_arabum%c2%bb_eine_altkatalanische_sprichw%c3%b6rter-Uns_sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/obra/Mettmann,_Walter_(1989):_%C2%ABProverbia_arabum%C2%BB_eine_altkatalanische_sprichw%C3%B6rter-Uns_sentenzensammlung' => '/obra/Mettmann%2C_Walter_%281298%29%3A_«Proverbia_arabum»_eine_altkatalanische_sprichwörter-Uns_sentenzensammlung%2C_ed._1989',
    '/p/A_judici_i_pagar%C2%ABlo%C2%BB_judicat' => '/p/A_judici_i_pagar_«lo»_judicat',
    '/p/Com_un_eix_a_l%27aigua' => '/p/Com_un_peix_a_l%27aigua',
    '/p/Fer_uin_merder' => '/p/Fer_merder',
    '/p/Ni_fe_d%27enc%C3%A0rrec' => '/p/Ni_fet_d%27enc%C3%A0rrec',
    '/p/Ni_fe_d%27enc%c3%a0rrec' => '/p/Ni_fet_d%27enc%C3%A0rrec',
    '/p/Pel_setembre_o_desembre%2C_qui_tingui_blat%2C_que_en_sembri' => '/p/Pel_setembre%2C_qui_tingui_blat%2C_que_en_sembri',
    '/p/Posr_en_gu%C3%A0rdia' => '/p/Posar_en_guàrdia',
    '/p/Posra_barba' => '/p/Posar_barba',
    '/p/Qui_dolent_fou_a_Tortosa%2C_dolent_ser%C3%A0_a_TolosaQui_dolent_fou_a_Tortosa%2C_dolent_ser%C3%A0_a_Tolosa' => '/p/Qui_dolent_fou_a_Tortosa%2C_dolent_serà_a_Tolosa',
    '/p/Rompre-li_la_crisma' => '/p/Trencar_o_rompre_la_crisma',
];
