#!/usr/bin/env bash

if [ -n "${IN_NIX_SHELL}" ]; then
    echo "You are in a Nix shell. Commits are disabled."
    exit 1
fi

. "$(dirname -- "$0")/_/husky.sh"

if ! npm run check:code; then
    exit 1
fi

if ! npm run lint:dockerignore:images; then
    echo "Make sure src/images directory is ignored in Docker."
    exit 1
fi

if ! npm run lint:dockerignore; then
    echo "Make sure .dockerignore file exists."
    exit 1
fi
