#!/usr/bin/env bash

if [ -n "${IN_NIX_SHELL}" ]; then
    echo "You are in a Nix shell. Commits are disabled."
    exit 1
fi

. "$(dirname -- "$0")/_/husky.sh"

if ! yarn check:code; then
    exit 1
fi

if ! yarn docker:images:lint; then
    echo "Make sure src/images directory is ignored in Docker."
    exit 1
fi
